### ISSUE TITLE
transcribe_file_stream.py does not work because of server-side error 

### ISSUE THREAD

**Issue by sergiuchuckmisha** [soniox/soniox_examples#3]
trying to run `transcribe_file_stream.py` with Russian speaking voice in Flac format got error on server side:
`python % python3 transcribe_file_stream.py
Traceback (most recent call last):
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/transcribe_file_stream.py", line 19, in <module>
    main()
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/transcribe_file_stream.py", line 8, in main
    result = transcribe_file_stream(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/soniox/transcribe_file.py", line 184, in transcribe_file_stream
    return transcribe_iter_bytes_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/soniox/transcribe_file.py", line 324, in transcribe_iter_bytes_stream
    return client.TranscribeCompleteStream(config, iter_audio)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/soniox/speech_service.py", line 194, in TranscribeCompleteStream
    for resp_result in self.TranscribeStream(config, iter_audio):
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/soniox/speech_service.py", line 176, in TranscribeStream
    for response in responses:
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/_/IdeaProjects/hw/soniox_examples/python/venv/lib/python3.11/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "<audio_decode_error> Error decoding input audio."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:35.193.130.106:443 {grpc_message:"<audio_decode_error> Error decoding input audio.", grpc_status:3, created_time:"2023-11-07T22:24:08.96267+02:00"}"
>
`

`python % python3 --version                
Python 3.11.3`

**Comment by klemensimonic2** [comment]
Please follow the steps provided in our [Quickstart](https://soniox.com/docs/quickstart/index.html) tutorial and you will be able to correctly and successfully use Soniox.
